catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
packages:
  - permix
  - docs
  - examples/*
catalog:
  '@antfu/eslint-config': ^7.6.1
  '@commitlint/cli': ^20.4.2
  '@commitlint/config-conventional': ^20.4.2
  '@eslint-react/eslint-plugin': ^2.13.0
  '@eslint/js': ^10.0.1
  '@orpc/server': ^1.13.5
  '@remixicon/react': ^4.9.0
  '@tailwindcss/postcss': ^4.2.1
  '@trpc/client': ^11.10.0
  '@trpc/server': ^11.10.0
  '@types/cors': ^2.8.19
  '@types/express': ^5.0.6
  '@types/mdx': ^2.0.13
  '@types/node': ^25.3.2
  '@types/pg': ^8.16.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vercel/analytics': ^1.6.1
  '@vitejs/plugin-react': ^5.1.4
  '@vitejs/plugin-vue': ^6.0.4
  '@vue/tsconfig': ^0.8.1
  autoprefixer: ^10.4.27
  class-variance-authority: ^0.7.1
  cors: ^2.8.6
  dotenv: ^17.3.1
  drizzle-kit: ^0.31.9
  drizzle-orm: ^0.45.1
  elysia: ^1.4.26
  eslint: ^10.0.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.5.2
  express: ^5.1.0
  fastify: ^5.7.4
  fumadocs-core: 16.0.7
  fumadocs-mdx: 13.0.5
  fumadocs-twoslash: ^3.1.13
  fumadocs-ui: 16.0.7
  globals: ^17.3.0
  hono: ^4.12.3
  husky: ^9.1.7
  lucide-react: ^0.575.0
  next: ^16.1.6
  npm-run-all2: ^8.0.4
  pg: ^8.19.0
  postcss: ^8.5.6
  react: ^19.2.0
  react-dom: ^19.2.4
  solid-js: ^1.9.11
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.1
  taze: ^19.9.2
  tsx: ^4.21.0
  twoslash: ^0.3.6
  typescript: ^5.9.3
  typescript-eslint: ^8.56.1
  vite: ^7.3.1
  vite-plugin-solid: ^2.11.10
  vite-tsconfig-paths: ^6.1.1
  vue: ^3.5.29
  vue-tsc: ^3.2.5
  zod: ^4.3.6
catalogs:
  permix:
    '@babel/preset-react': ^7.28.5
    '@babel/preset-typescript': ^7.28.5
    '@rollup/plugin-babel': ^6.1.0
    '@solidjs/testing-library': ^0.8.10
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.3.2
    '@types/express': ^5.0.6
    '@types/node': ^25.3.2
    '@types/react': ^19.2.14
    '@types/supertest': ^7.2.0
    '@vitejs/plugin-react': ^5.1.4
    '@vitest/coverage-v8': ^4.0.18
    '@vue/test-utils': ^2.4.6
    babel-preset-solid: ^1.9.10
    happy-dom: ^20.7.0
    react-dom: ^19.2.4
    supertest: ^7.2.2
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite-plugin-solid: ^2.11.10
    vitest: ^4.0.18
    vue: ^3.5.17
    zod: ^4.3.6
